# Generated by Django 4.0.2 on 2022-02-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cve_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskprofile',
            name='support_url',
        ),
        migrations.AddField(
            model_name='cve',
            name='support_url',
            field=models.URLField(default='https://support.lexmark.com'),
            preserve_default=False,
        ),
    ]
