# Generated by Django 4.0.2 on 2022-02-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cve_public_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='public_release_date',
            field=models.DateField(blank=True, help_text='CVE release date', null=True),
        ),
    ]
