# Generated by Django 4.0.2 on 2022-04-02 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_remove_firmwarereference_affected_build_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cves_last_updated', models.DateTimeField(verbose_name='CVE Data Last Updated')),
                ('platform_version', models.CharField(max_length=25, verbose_name='CVE Tracking Platform Version')),
                ('admin_contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Current Admin User')),
            ],
        ),
    ]
