# Generated by Django 4.0.2 on 2022-04-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sysinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='sysinfo',
            name='name',
            field=models.CharField(default='SysInfo', editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='Site settings name - must not be changed'),
        ),
    ]
