# Generated by Django 4.0.2 on 2022-04-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_sysinfo_id_sysinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmwarereference',
            name='device_type',
            field=models.CharField(choices=[('xml', 'Moja/Claiborne'), ('ucf', 'HomeStretch'), ('combo', 'Winners Circle'), ('na', 'Unknown')], default='na', max_length=5),
        ),
    ]
