# Generated by Django 4.0.2 on 2022-02-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerableDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=15)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('firmware_major', models.PositiveSmallIntegerField(verbose_name='Firmware Major')),
                ('firmware_minor', models.PositiveSmallIntegerField(verbose_name='Firmware Minor')),
                ('firmware_build', models.CharField(max_length=8, verbose_name='Firmware Build')),
                ('vulnerable_cves', models.ManyToManyField(to='core.CVE')),
            ],
        ),
    ]
