# Generated by Django 4.0.2 on 2022-02-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vulnerabledevice',
            options={'verbose_name': 'Vulnerable Device'},
        ),
    ]
