# Generated by Django 4.0.2 on 2022-02-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cve_public_release_date'),
        ('analytics', '0003_alter_vulnerabledevice_vulnerable_cves'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=15)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('firmware_major', models.PositiveSmallIntegerField(verbose_name='Firmware Major')),
                ('firmware_minor', models.PositiveSmallIntegerField(verbose_name='Firmware Minor')),
                ('firmware_build', models.CharField(max_length=8, verbose_name='Firmware Build')),
                ('vulnerable_cves', models.ManyToManyField(blank=True, null=True, to='core.CVE', verbose_name='Vulnerable CVEs')),
            ],
            options={
                'verbose_name': 'Device',
            },
        ),
        migrations.DeleteModel(
            name='VulnerableDevice',
        ),
    ]
