# Generated by Django 4.0.2 on 2022-02-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_device_delete_vulnerabledevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
