# Generated by Django 4.0.2 on 2022-02-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_firmwarereference_affected_build_and_more'),
        ('analytics', '0005_device_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='vulnerable_cves',
            field=models.ManyToManyField(blank=True, to='core.CVE', verbose_name='Vulnerable CVEs'),
        ),
    ]
